language: java
jdk:
  - oraclejdk8
script: ./gradlew build --scan -s
install: true
notifications:
  email:
    recipients:
      - "dmulloy2@live.com"
    on_success: change
    on_failure: always